### Local API Tests

### Get all contacts
GET http://localhost:3000/contacts

### Get one contact (replace with actual ID)
GET http://localhost:3000/contacts/68274f20166df25e488d40e6

### Welcome message
GET http://localhost:3000/


### Render API Tests (replace with your actual Render URL)

### Get all contacts
GET https://cse-341spring.onrender.com/contacts

### Get one contact (replace with actual ID)
GET https://cse-341spring.onrender.com/contacts/68274f20166df25e488d40e6

### Welcome message
GET https://cse-341spring.onrender.com/